### ISSUE TITLE
Remove unused color attr

### ISSUE THREAD

**Issue by curtpm** [appnexus/mobile-sdk-android#16]
the "color" attr located here:
https://github.com/appnexus/mobile-sdk-android/blob/master/sdk/res/values/attrs.xml#L54

is a generic name and conflicts with the official "color" name that is part of appCompat-v21 

it appears to not be referenced anywhere in the code and should be removed.

**Comment by jenzz** [comment]
This seems to be fixed via https://github.com/appnexus/mobile-sdk-android/commit/74a99663a983d9379ac5533b4f9d5f70ee1ae2c6.
