### ISSUE TITLE
Memory Leak With GooglePlay adapter

### ISSUE THREAD

**Issue by curtpm** [appnexus/mobile-sdk-android#19]
Currently the logic inside of the GooglePlay SDK Adapter has a massive memory leak when used with Fragments. 

Both GooglePlayDFPBanner and GooglePlayServicesBanner classes register a Application.ActivityLifecycleCallbacks as soon as requestAd is called.

Then they uses the LifecycleCallbacks to forward the calls to onPause, onResume and OnDestroy (where the listener is unbound).

There are multiple issues with this approach.

1. onPause onResume onDestroy should be called in sync with the activity that the view is bound to.
   LifecycleCallbacks are invoked for every Activity owned by the application. This means that every view   will wake up when any activity starts. 

2. If a AdView is attached to a Fragment then the calls to onPause onResume onDestroy are completely missed if the Fragment is created after an Activity is already started. 

3. Because the LifecycleCallbacks is only deregistered in Activity onDestroy, if an Activity has multiple  Fragments created and Destroyed the entire Fragment will be leaked until the Activities onDestroy is called allowing the hard reference chain to be GC'ed.

4. Currently the logic to forward the explicit call to destroy to a Meditated SDK is also broken. 
    If a AdRequest is made the LifecycleCallbacks are registered.  
    Then before the ad is successfully loaded the screen is killed and destroy is called.
    Because AdView#lastDisplayable is ONLY set when "display" is called, this will fail the null check in    "destroy" and will NOT forward on the call causing the issues mentioned in issue 2 and 3 above. 

The correct implementation should behave as follows:

1. WebView lifecycle should be explicitly called from their owner (Activity or Fragment). 
   a. User is responsible for calling AdView#onResume, onPause, and destroy for every AdView. 

2. Calls to the lifecycle methods mentioned above should immediately be forwarded to the corresponding Mediation SDK that is active.

**Comment by anwzhang** [comment]
Developers can now pass BannerAdView.activityOnResume(), BannerAdView.activityOnPause(), BannerAdView.activityOnDestroy in the activity’s life cycle. Here’s the commit that solved the issue:

https://github.com/appnexus/mobile-sdk-android/commit/e4135290805007de16527fcc64d27090872b5c44
