### ISSUE TITLE
Memory leak: GooglePlayDFPBanner

### ISSUE THREAD

**Issue by jenzz** [appnexus/mobile-sdk-android#23]
This is a follow-up to the issue @curtpm created almost 2 years ago: https://github.com/appnexus/mobile-sdk-android/issues/19

Now that the user of `GooglePlayDFPBanner` manually forwards the respective lifecycle methods (`onResume()`, `onPause()`, etc),
registering an `ActivityLifecycleCallbacks` is no longer necessary.

Can you please strip out those listeners entirely as it is **still leaking memory** as described in the old issue.

Consequently, `GooglePlayDFPBanner` would also no longer need to hold a strong reference to the hosting Activity via `adViewActivity`.

**Comment by josecu** [comment]
My sincere apologies for the delay in responding. The change will be in our next release.

Cheers,
Jose

**Comment by josecu** [comment]
This was released in RC2.15.1.
