### ISSUE TITLE
NullPointerException in MRAIDAdActivity

### ISSUE THREAD

**Issue by mdcdeveloper** [appnexus/mobile-sdk-android#28]
Hi,

In MRAIDAdActivity you check that the first view is an AdWebView or not, but it can lead to a NullPointerException.
The check:
`
if(AdView.mraidFullscreenContainer.getChildAt(0) instanceof AdWebView) {
     this.webView = (AdWebView)AdView.mraidFullscreenContainer.getChildAt(0);
}`

A NPE can happen if the first child is not an AdWebView here:
`if(this.webView.getContext() instanceof MutableContextWrapper) {
	((MutableContextWrapper)this.webView.getContext()).setBaseContext(this.adActivity);
}`

This is the related StackTrace:

> Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context com.appnexus.opensdk.AdWebView.getContext()' on a null object reference
   at com.appnexus.opensdk.MRAIDAdActivity.create(MRAIDAdActivity.java:51)
   at com.appnexus.opensdk.AdActivity.onCreate(AdActivity.java:91)

**Comment by avohraa** [comment]
Closing this issue because it has been open for a long time and there are no recent interactions on this.
If this is still relevant in the latest SDK version feel free to re-open the ticket.
