### ISSUE TITLE
You requested an Ad larger than the measured ad space

### ISSUE THREAD

**Issue by alex-hryzak** [appnexus/mobile-sdk-android#29]
In some circumstances (depending on device screen and resolution of banner), it's not possible to use BannerAdView.resize_ad_to_fit_container, failing with an error message like "E103: You requested an Ad larger than the measured ad space. Ad space size: 328x100, request size: 358x100". The bug seems to be an invalid comparison of dips agains pixels (BannerAdView.java:235):

float density = this.getContext().getResources().getDisplayMetrics().density;
int measuredWidth = (int)((float)(right - left) / density + 0.5F);
int measuredHeight = (int)((float)(bottom - top) / density + 0.5F);
if(this.requestParameters.getAllowedSizes() == null && (measuredWidth < this.requestParameters.getAdWidth() || measuredHeight < this.requestParameters.getAdHeight()) && measuredWidth > 0 && measuredHeight > 0) {
    Clog.e(Clog.baseLogTag, Clog.getString(string.adsize_too_big, measuredWidth, measuredHeight, this.requestParameters.getAdWidth(), this.requestParameters.getAdHeight()));

Where measuredWidth/measuredHeight are already converted to dip, but getAdWidth()/getAdHeight() are still pixels.

**Comment by sgallo0692** [comment]
Hi Alex,

Thanks for reaching out! Please submit SDK issues through our support portal at support.appnexus.com. By submitting through our portal, we can investigate and track the issue more efficiently. Please let me know if you have questions!

**Comment by sgallo0692** [comment]
Hi Alex,

I've actually made a mistake, our latest release resolves this issue. Please let us know if you continue to experience any issues!

**Comment by alex-hryzak** [comment]
Still not fixed ... see BannerAdView.java line 272.
