### ISSUE TITLE
Make client app access variable userInteracted

### ISSUE THREAD

**Issue by Larfo** [appnexus/mobile-sdk-android#32]
Our app need to catch when the user interacts with an ad in order to prevent a viewpager of swiping when the user swipe in an ad. In order to do this the variable userInteracted in AdWebView.class can be made available for the app. A fix is to make AdWebView class public and userInteracted public static.

**Comment by Kowshickkarthick** [comment]
Hi @Larfo ,

Thanks for reaching out! Please submit SDK issues/feature requests through our support portal at support.appnexus.com. By submitting through our portal, we can investigate and track the issue/feature requests more efficiently. Please let me know if you have questions!

-Kowshick

**Comment by avohraa** [comment]
Closing this issue because it has been open for a long time and there are no recent interactions on this.
If this is still relevant in the latest SDK version feel free to re-open the ticket.
