### ISSUE TITLE
Leak AdActivity

### ISSUE THREAD

**Issue by asalliou** [appnexus/mobile-sdk-android#37]
Hi,

I'm experiencing a leak using the app nexus android SDK 4.10 :

![screenshot_2018-08-07-14-43-37](https://user-images.githubusercontent.com/404209/43762879-7374c5f4-9a29-11e8-8681-4915df455569.png)

Best regards
Antoine

**Comment by avohraa** [comment]
Closing this issue because it has been open for a long time and there are no recent interactions on this.
If this is still relevant in the latest SDK version feel free to re-open the ticket.
