### ISSUE TITLE
After upadating the exisiting to 'com.appnexus.opensdk:appnexus-sdk:[5,6) ,ads are not coming

### ISSUE THREAD

**Issue by pretivj** [appnexus/mobile-sdk-android#38]
After upadating the exisiting 'com.appnexus.opensdk:appnexus-sdk:[3,4) to 'com.appnexus.opensdk:appnexus-sdk:[5,6) ,ads are not coming

Getting the warning as "OPENSDK: An attempt to request an ad has been made with insufficient size information. Please provide a size, max size, or use fill_parent as the dimensions for your BannerAdView."

Please tell me where i miss the implementation.previously in [3,4] it works fine.

Thanks in advance

**Comment by Kowshickkarthick** [comment]
Hi,

Starting with SDK v4.0 size information is mandatory for making an ad call.
Depending on your use-case, you can pass size information to SDK using one of the below API's 

- setAdSize(int w, int h) 
- setAdSizes(ArrayList<AdSize> adSizes)
- setMaxSize(int maxW, int maxH)

**Comment by Kowshickkarthick** [comment]
Hi @pretivj,

Closing this ticket for now.
If you feel you need further assistance on this, please reach out through our support portal https://support.appnexus.com. That would help us to track the issue better and solve it for you.

Thanks,
Kowshick S
