### ISSUE TITLE
Crashes because of library's themes

### ISSUE THREAD

**Issue by cell-android** [appnexus/mobile-sdk-android#41]
We observed lots of crashes in our crash reports after including the "appnexus-sdk" and "mediatedviews:appnexus-googleplay-mediation" in our app. Our investigation showed that in some cases our app theme gets overridden by the theme of the library. Since a theme name like "AppBaseTheme" is quite common and the library itself doesn't need a theme, we would strongly advice to remove it from the library or to rename it to something more specific. In order to fix the bug, we had to rename our app's theme to make it work again. 

This bug occurres only on some devices but most of them were running Android 4.4.2. We could reproduce the bug by launching our app in an Android 4.4.2 emulator.

**Comment by avohraa** [comment]
@cell-android we will look into it, and get back to you. Although you already have a solution to it, we will look into the changes on our end and test it to be out in next release maybe.
