### ISSUE TITLE
Banner Size is -1 when using Google Smartbanner

### ISSUE THREAD

**Issue by JErmert** [appnexus/mobile-sdk-android#42]
Hey,
we are mediating Appnexus through Google Admob. Using the mediation adapter the bannersize is not measured correctly when you are using Smart Banner as Size in Admob/DFP.         

appNexusAdView.setAdSize(adSize.getWidth(), adSize.getHeight()); sets -1, 50 as Adsize and therefore does not work. 

Here is some information about smart banners from Google:
https://developers.google.com/admob/android/banner#smart_banners

**Comment by avohraa** [comment]
Closing this issue because it has been open for a long time and there are no recent interactions on this.
If this is still relevant in the latest SDK version feel free to re-open the ticket.
