### ISSUE TITLE
Disable showing ads

### ISSUE THREAD

**Issue by omegasoft7** [appnexus/mobile-sdk-android#44]
Is there any way to disable SDK for providing ads?
In our App, we are looking for a way to disable AppNexus ads via a feature switch from our side. Are there any configurations in the SDK that we can set to force AppNexus SDK stops requesting and showing ads?

**Comment by Daniel-Berger** [comment]
Is it possible to not call loadAd in situations where you don't want to load a creative?

**Comment by omegasoft7** [comment]
I tried with not calling `loadAd()` but after sometime I saw that add was loading itself again!
I tried with not calling `loadAd()` and also prevent adding `addCustomKeywords`, but I saw the same result at the end, Ad was loading again but with a bigger delay!

**Comment by omegasoft7** [comment]
I just tried removing `setInventoryCodeAndMemberID` and it seems it stopped requesting ads 👍 It seems that this is what I needed.

**Comment by Daniel-Berger** [comment]
Glad to hear.
