### ISSUE TITLE
Ads SDK uses HTTP therefore doesnt work on Android 9+

### ISSUE THREAD

**Issue by frankkienl** [appnexus/mobile-sdk-android#45]
https://developer.android.com/training/articles/security-config#base-config
Since Android 9, HTTP is no longer allowed by default.

So I added a network-security-config, to allow their domain as HTTP.
But that may be useless, when all the ads they serve may come from different domains. 
I don't want to enable HTTP globally.

```
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
   <domain-config cleartextTrafficPermitted="true">
       <domain includeSubdomains="true">adnxs.com</domain>
   </domain-config>
</network-security-config>
```

**Comment by avohraa** [comment]
Hey,

This part of your issue is unclear to me: ```I don't want to enable HTTP globally.```

But for a quick solution, you can force the SDK to use HTTPS using ```SDKSettings.useHttps(true);```.

**Comment by frankkienl** [comment]
Ah, thanks!
