### ISSUE TITLE
Resources$NotFoundException Android API 21/22 BannerAdView initialization

### ISSUE THREAD

**Issue by joseluiscadena** [appnexus/mobile-sdk-android#46]
When I try to load a banner in an Android API 21 i got the following crash
![image](https://user-images.githubusercontent.com/1645922/66069413-f0964f80-e514-11e9-9b0a-a461d4d978b8.png)
As you can see apparently there is one resource not found which generates this crash. Only happens in Android API 21 
I thing that maybe this error is happening un general to everyone ¿Can you help me?
This is part of my code, debugging, everything is ok, until `bannerAdView.adSizes = ArrayList<AdSize>(bannerSizes)` then immediatly app crashes
![image](https://user-images.githubusercontent.com/1645922/66069545-305d3700-e515-11e9-86cd-8793bba39382.png)

**Comment by Sloy** [comment]
Yep, happening to us too. Seems to be related to this issue https://issuetracker.google.com/issues/141132133

Although we're using appcompat 1.0.2

**Comment by Sloy** [comment]
More info: Some transitive dependencies are pulling appcompat 1.1.0, which causes crahes with the WebView (see issue link above).

Here is our workaround for now:
```
configurations.all {
    resolutionStrategy {
        force 'androidx.appcompat:appcompat:1.1.0-rc01'
    }
}
```

**Comment by joseluiscadena** [comment]
Thanks for sharing this to me. Apparently it's working correctly. I tried to use the latest version but it didn't work, the only one that works is `androidx.appcompat:appcompat:1.1.0-rc01`

<img width="914" alt="imagen" src="https://user-images.githubusercontent.com/1645922/66670061-76ee1800-ec1e-11e9-8bba-b2bd0d74820a.png">

BTW I also work for adevinta 👍

**Comment by Sloy** [comment]
Haha seriously?? The world is so small, and Adevinta is so big!! 😂

**Comment by srijithnair** [comment]
@joseluiscadena - please confirm that this can be closed.

**Comment by avohraa** [comment]
Closing this issue because it has been open for a long time and there are no recent interactions on this.
If this is still relevant in the latest SDK version feel free to re-open the ticket.
