### ISSUE TITLE
Allow access to localStorage

### ISSUE THREAD

**Issue by johanhasselstrom** [appnexus/mobile-sdk-android#47]
Access to localStorage is disabled as default in WebViews. Would you consider enabling it by setting domStorageEnabled=true? Either by default or configurable via SDKSettings.

This would align the settings and possibilities with iOS.

**Comment by avohraa** [comment]
Closing this issue because it has been open for a long time and there are no recent interactions on this.
If this is still relevant in the latest SDK version feel free to re-open the ticket.
