### ISSUE TITLE
vulnerable implementation of ssl error handling in webview

### ISSUE THREAD

**Issue by micHar** [appnexus/mobile-sdk-android#48]
Google Play started complaining recently:

> Your app is using an unsafe implementation of WebViewClient.onReceivedSslError handler. Please see this Google Help Center article for details, including the deadline for fixing the vulnerability.

https://support.google.com/faqs/answer/7071387

Seems that your implementation might be at fault:

https://github.com/appnexus/mobile-sdk-android/blob/8d4c45f52713b4a504b13e650517dafb647146df/sdk/src/com/appnexus/opensdk/AdWebView.java#L515

**Comment by avohraa** [comment]
We are looking into it. 

> Expect a resolution to this in our next release.
