### ISSUE TITLE
TreeWalker eats CPU

### ISSUE THREAD

**Issue by AAverin** [appnexus/mobile-sdk-android#51]
I have been looking into some lags in the app and when the app is completely idle and there are no ads visible on the screen at the moment, CPU profiling shows this picture.

![image](https://user-images.githubusercontent.com/1481332/92257522-a8766e80-eed5-11ea-87be-ba8fe5586cec.png)

What is TreeWalker and why does it run every frame making expensive calls to get display info and real size?

**Comment by Kowshickkarthick** [comment]
Hi @AAverin 

TreeWalker is part of OpenMeasurment SDK integrated with Xandr SDK.
This is for calculating Viewability of the Ad being rendered and gets reported in our Viewability metrics.
It runs every 200ms to detect if the Ad is on screen or not and also the actual co-ordinates fo the ad on screen.

**Comment by AAverin** [comment]
@Kowshickkarthick I understand that it's probably a part of iAB implementation, but I didn't find a way to reach to them directly. I am also trying to push this bug through other channels and also have reported it to Google Ads team.
I get the need to detect ads viewability, but there should be a way to avoid calling `getRealSize` that twice every 200ms. The value for `getRealSize` would only change with device rotation. Sure there should be a way to pre-calculate or cache that value.

At the moment this `walking` is responsible for 60% of CPU load in our app. This basically means that if we want to make sure our app is performant (as native app should be), we should squeeze all our business logic and view calculations into 40% that are left. So out of 16ms per frame available for 60fps draws, we have just 7 or even less if we want to push to 90fps.

**Comment by srijithnair** [comment]
Escalated to IAB via their slack channel. They are reviewing this with their engineers.

**Comment by avohraa** [comment]
Closing this issue because it has been open for a long time and there are no recent interactions on this.
If this is still relevant in the latest SDK version feel free to reach out through the [support team](https://help.xandr.com/)

**Comment by AAverin** [comment]
@avohraa shouldn't this stay open until any feedback from IAB team comes back? Was there any feedback? Is there a related issue made for Google?

**Comment by Kowshickkarthick** [comment]
We no longer release source code updates of Android SDK to Github. 
And this space is not monitored.
Please contact your account managers or submit a ticket via the Customer Support Portal: https://help.xandr.com/ if you have any questions.
