### ISSUE TITLE
Mediation Updates

### ISSUE THREAD

**Issue by Kowshickkarthick** [appnexus/mobile-sdk-android#52]
We are seeing little to no usage for some of the mediation adapters that are included in the Mobile SDK. This I2I is to notify our SDK users that we will NOT be actively maintaining or supporting the adapters in the list (see below) from the next SDK release onwards.

1) Amazon
2) InMobi
3) Millennial Media
4) Mopub

We will stop uploading them to Maven.
Please note that we do not plan to remove/deprecate the aforementioned adapters in code, but rather we will be moving these adapters to a different folder within the Mobile SDK repository.
If there is enough interest in certain mediation adapter(s), we will remain open to the idea of adding them back to our list of supported adapters.
Our hope with this change is that we will be able to provide faster and more frequent updates to the remaining subset of supported mediation adapters in the future.
If you have any questions/comments please let us know either via GitHub/or via Xandr Support.

**Comment by ppuviarasu** [comment]
Implemented & released with v7.7
