### ISSUE TITLE
No null check on adListener for onLazyAdLoaded in AdView

### ISSUE THREAD

**Issue by iliaskomp** [appnexus/mobile-sdk-android#54]
In `AdView` [here](https://github.com/appnexus/mobile-sdk-android/blob/cb2679bae41e76a12f7836e21eb5a125061ced70/sdk/src/com/appnexus/opensdk/AdView.java#L1287) there is no null check around the adListener call (in other similar code in the class there is null check).

This is critical since it provokes crashes when the adListener is null.

**Comment by srijithnair** [comment]
hi @iliaskomp - thanks, we will look into this.

**Comment by srijithnair** [comment]
To be released as part of v7.8.1 - ETA, this week.

**Comment by avohraa** [comment]
Released as part of v7.8.1.
