### ISSUE TITLE
Leak caused by AdSessionContext in AdWebView

### ISSUE THREAD

**Issue by OFmarting** [appnexus/mobile-sdk-android#57]
Hi,
It seems that the `AdSessionContext` in the `AdWebView` can cause memory leaks. I could also reproduce it in the `SimpleDemo` by adding `implementation "com.squareup.leakcanary:leakcanary-android:2.5"` to the `build.gradle` file of the app module and opening the `BannerActivity` and rotating the device a few times. I also attached a file of the leak trace [here](https://github.com/appnexus/mobile-sdk-android/files/5703852/Leak.txt).

The issue seems to be that the [initAdSession](https://github.com/appnexus/mobile-sdk-android/blob/46d1806d19a28e34666e776dd6d06db16af8303e/sdk/src/com/appnexus/opensdk/AdWebView.java#L442) method can be invoked in the `AdWebView` after it was destroyed. The `AdWebView` can be destroyed before [initAdSession](https://github.com/appnexus/mobile-sdk-android/blob/46d1806d19a28e34666e776dd6d06db16af8303e/sdk/src/com/appnexus/opensdk/AdWebView.java#L442) is invoked when for example [success](https://github.com/appnexus/mobile-sdk-android/blob/46d1806d19a28e34666e776dd6d06db16af8303e/sdk/src/com/appnexus/opensdk/AdWebView.java#L429) is invoked before on the `AdWebView`. A call to [success](https://github.com/appnexus/mobile-sdk-android/blob/46d1806d19a28e34666e776dd6d06db16af8303e/sdk/src/com/appnexus/opensdk/AdWebView.java#L429) could eventually lead to the `AdWebView` being destroyed. In this method [onReceiveAd](https://github.com/appnexus/mobile-sdk-android/blob/46d1806d19a28e34666e776dd6d06db16af8303e/sdk/src/com/appnexus/opensdk/AdWebView.java#L679) is invoked on the `caller_requester` which in turn could lead to a `destroy` call on the `AdWebView` [here](https://github.com/appnexus/mobile-sdk-android/blob/46d1806d19a28e34666e776dd6d06db16af8303e/sdk/src/com/appnexus/opensdk/AdViewRequestManager.java#L170) in the `AdViewRequestManager`.

I think a solution might be to check [here](https://github.com/appnexus/mobile-sdk-android/blob/46d1806d19a28e34666e776dd6d06db16af8303e/sdk/src/com/appnexus/opensdk/AdWebView.java#L441) if the `AdWebView` is already destroyed. But there might also be another solution.

**Comment by avohraa** [comment]
Hi @OFmarting, we have noticed that the SimpleDemo app was missing to call `activityOnDestroy()` for the AdUnits when those were expected to be destroyed. We will be updating our Sample apps along with the documentation.

Meanwhile, could you please test if calling `adUnit.activityOnDestroy()`(when those are expected to be destroyed) fixes the memory leak for you.

**Comment by OFmarting** [comment]
Hi @avohraa,
We are already calling `activityOnDestroy()` on the Ad Units were they are expected to be destroyed. Does LeakCanary still report a leak for you after adding the call to `activityOnDestroy()` in the `SimpleDemo` App?

**Comment by avohraa** [comment]
Hi @OFmarting,

Thanks for confirming. 

Calling `activityOnDestroy()` helped us resolve the memory leak in the SimpleDemo app. But, when we tested further, we were able to replicate memory leaks, with lesser frequency. Thus, we have made a few changes towards its resolution, which is in testing.

We are planning to include those changes in the coming release. Which will still require the call to `activityOnDestroy()`.

**Comment by OFmarting** [comment]
Hi @avohraa,
I see. Thank you for the information.

**Comment by avohraa** [comment]
Hi @OFmarting,

This issue has been addressed in the latest release - https://github.com/appnexus/mobile-sdk-android/releases/tag/7.16

Let us know if that fixes your issue.

**Comment by OFmarting** [comment]
Hi @avohraa,
It seems that the memory leak is fixed in 7.16. 
However, I'm not sure if setting the context of the view to the application context [here](https://github.com/appnexus/mobile-sdk-android/blob/187d0945740a52088ed5ffed9ee3aa2e7a920327/sdk/src/com/appnexus/opensdk/AdWebView.java#L741) is optimal in this case since this will not prevent that [onPageFinished](https://github.com/appnexus/mobile-sdk-android/blob/187d0945740a52088ed5ffed9ee3aa2e7a920327/sdk/src/com/appnexus/opensdk/AdWebView.java#L415) is called.

**Comment by avohraa** [comment]
Hi @OFmarting,

Thanks for the confirmation.

We are removing the webviewClient [here](https://github.com/appnexus/mobile-sdk-android/blob/187d0945740a52088ed5ffed9ee3aa2e7a920327/sdk/src/com/appnexus/opensdk/AdWebView.java#L754) which will prevent `onPageFinished` to be called.

**Comment by OFmarting** [comment]
Hi @avohraa,
It seems that setting the `WebViewClient` to `null` has no effect. According to the documentation for [`setWebViewClient`](https://developer.android.com/reference/android/webkit/WebView#setWebViewClient(android.webkit.WebViewClient)) the parameter value cannot be `null`. Also, when removing [these two lines](https://github.com/appnexus/mobile-sdk-android/blob/master/sdk/src/com/appnexus/opensdk/AdWebView.java#L746-L747) in the code this [leak](https://github.com/appnexus/mobile-sdk-android/files/7114704/Leak.txt) is still occurring. I think it would be better to prevent that the `onPageFinished` method is called after `destroy` was called instead of changing the base context of the `WebView` to the Application Context in the destroy method.
