### ISSUE TITLE
onWindowVisibilityChanged() shouldn't trigger the load of the ad

### ISSUE THREAD

**Issue by gbero** [appnexus/mobile-sdk-android#59]
In our implementation, we create the `BannerAdView`, and add it to the view hierarchy. Doing so, shouldn't provoke the loading of the ad. Only a call to `loadAd()` should trigger that.

To reproduce the issue, inflate a `BannerAdView`, add it to your layout. The method `start()` gets called by the `onWindowVisibilityChanged()`

**Comment by gbero** [comment]
To create a workaround on our side for this issue we dived into the Xandr SDK source code. 
We call `BannerAdView.init()` which will set the `loadedOffscreen` boolean to true, hence it won’t call `start()` in the `onWindowVisibilityChanged()` function. `start()` will only be called by the client call to `loadAd()`

**Comment by avohraa** [comment]
Hey @gbero

Are you using `autoRefresh` or `shouldReloadOnResume`?

**Comment by gbero** [comment]
we set `autoRefreshInterval = 0`
we never call `setShouldReloadOnResume()`

**Comment by avohraa** [comment]
Okay @gbero, we are unable to replicate it after setting autoRefreshInterval as 0. Could you please elaborate on the replication steps?

**Comment by gbero** [comment]
Hey @avohraa,

Using your example : `BannerActivity.kt`
Remove the line `banner.loadAd()`
The ad will load anyway.

Hope this helps.

**Comment by gbero** [comment]
Changing `autoRefreshInterval = 0` has no effect.

<img width="417" alt="Screenshot 2021-02-17 at 19 41 30" src="https://user-images.githubusercontent.com/2629641/108251781-25319800-7158-11eb-8e13-23823769a821.png">

**Comment by avohraa** [comment]
@gbero, that surely is strange, and we would like to get rid of it. We have tried the changes in the `BannerActivity.kt` that you mentioned but was unable to replicate the issue.

Technically, there's an initial check ```if (loadAdHasBeenCalled || shouldReloadOnResume || (period > 0))``` inside `onWindowVisibilityChanged` which means it will start fetching the Ad if either of the following condition is true, before loadAd() is called:
- shouldReloadOnResume
- autoRefreshInterval > 0

And the stranger part is that you are facing an issue which we are unable to replicate after turning off the autoRefresh, even with the same app that you are using. To proceed further on this we will need to replicate it first.

We would want to know about the cases where it can be replicated.

**Comment by gbero** [comment]
In https://github.com/appnexus/mobile-sdk-android/blob/master/sdk/src/com/appnexus/opensdk/BannerAdView.java#L908

I see : `if (!loadAdHasBeenCalled || shouldReloadOnResume || (period > 0)) {`

There's a negation over `loadAdHasBeenCalled`

**Comment by avohraa** [comment]
Ohh! Got it. This will be addressed in the next release.

**Comment by gbero** [comment]
Were you able to reproduce ? I'm relying on `master` branch.

**Comment by avohraa** [comment]
@gbero Can you check if the latest release fixes this issue?

**Comment by gbero** [comment]
@avohraa lgtm! 👍
