### ISSUE TITLE
AdText single quotes are not escaped

### ISSUE THREAD

**Issue by Gaetan** [appnexus/mobile-sdk-android#61]
If you set the `adText` property for the video player and you include a single quote, the video player does not render.

I set the value to `Today's ad`, put a breakpoint on this line: https://github.com/appnexus/mobile-sdk-android/blob/fa4b4bc1a9eade9c5390a22b21035293c54aaad8/sdk/src/com/appnexus/opensdk/VideoImplementation.java#L105
and got this as a value:
```javascript:window.createVastPlayerWithContent('PD...D4=','{"partner":{"name":"Appnexus","version":"7.13.1"},"entryPoint":"BANNER","videoOptions":{"adText":"Today's ad","learnMore":{"enabled":false},"showMute":true,"allowFullscreen":true,"showFullScreenButton":true}}')```

The single quote in the string ends the quote of the second parameter of `createVastPlayerWithContent`.

Double quotes are escaped correctly, so the line above could be changed to `"javascript:window.createVastPlayerWithContent(\"%s\",\"%s\")"`

Aside from that, I noticed that you could also inject HTML for the ad text. E.g. `<h1><marquee>I AM TOO BIG</marquee></h1>`

**Comment by Kowshickkarthick** [comment]
We have made the code changes fixing this issue.
This will be fixed in our v7.15 release. ETA June 21-25.

**Comment by avohraa** [comment]
This has been addressed in the latest release - https://github.com/appnexus/mobile-sdk-android/releases/tag/7.15

Closing it out. Feel free to reopen in case of an issue.
