### ISSUE TITLE
Interstitial dismissed before Webview opened

### ISSUE THREAD

**Issue by maximou4391** [appnexus/mobile-sdk-android#62]
Hello,
We have a problem when using showWithAutoDismissDelay on Android (sdk version 7.13.1), 
we put the following:
`iav.setCloseButtonDelay(0);
iav.showWithAutoDismissDelay(7);
iav.setDismissOnClick(true);`

when user click on the ad for some reason the ad is destroyed after the click and then few seconds after only the webview is displayed.

Is there a way to not have the ad disappearing and show the webview only when ready?

Knowing on the collasped callback we did that:
`@Override
            public void onAdCollapsed(AdView iav) {
                // Interstitial closed, the advertisement needs to be destroyed to avoid memory leak
                iav.destroy();
                Timber.d("Xandr Interstitial collapsed");

            }`

What would be the reason of the ad being destroyed before the actual clicked link is displayed in the webview?
Thanks a lot in advance,
Regards,
Maxime.

**Comment by avohraa** [comment]
@maximou4391 

We tried replicating the issue described here, but couldn't. 

Please provide more info, such as the placement / creative (that you are using), and maybe a screen recording of the issue that you are facing, with replication steps.

**Comment by maximou4391** [comment]
Hello @avohraa ,
Thanks for your reply!

placement is "interstitial" in debug mode in Android

![interstitial](https://user-images.githubusercontent.com/13694761/122584834-1c47c900-d05b-11eb-81b9-b2ace012fd4e.gif)

You can see here that I click on the interstitial some seconds after it appeared. And there is a delay between when the interstitial is dismissed and the webview is loaded.

Regards,

Maxime.

**Comment by avohraa** [comment]
This has been addressed in the latest release - https://github.com/appnexus/mobile-sdk-android/releases/tag/7.15

Closing it out. Feel free to reopen in case of an issue.

**Comment by maximou4391** [comment]
Awesome @avohraa I will check that!
