### ISSUE TITLE
NullPointerException in AdViewRequestManager.processNextAd

### ISSUE THREAD

**Issue by maxacmaxac** [appnexus/mobile-sdk-android#64]
Please fix Exception.

Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'java.lang.String com.appnexus.opensdk.ut.adresponse.BaseAdResponse.getContentSource()' on a null object reference

com.appnexus.opensdk.AdViewRequestManager.processNextAd (AdViewRequestManager.java:221)
com.appnexus.opensdk.AdViewRequestManager.processUTResponse (AdViewRequestManager.java:202)
com.appnexus.opensdk.AdViewRequestManager.onReceiveUTResponse (AdViewRequestManager.java:181)
com.appnexus.opensdk.ut.UTAdRequest.processResponse (UTAdRequest.java:331)
com.appnexus.opensdk.ut.UTAdRequest.execute (UTAdRequest.java:88)
com.appnexus.opensdk.RequestManager.execute (RequestManager.java:66)
com.appnexus.opensdk.AdFetcher$RequestHandler.handleMessage (AdFetcher.java:259)
android.os.Handler.dispatchMessage (Handler.java:110)
android.os.Looper.loop (Looper.java:219)
android.os.HandlerThread.run (HandlerThread.java:67)

**Comment by avohraa** [comment]
@maxacmaxac 

Is that a reproducible exception? If so, please share the use case and reproduction steps for this exception.

Please share the following details, for us to look into it:
* SDK version
* Placement ID / Creative ID
* Reproduction steps

**Comment by maxacmaxac** [comment]
@avohraa 

exception is not reproducible. Found in crashlytics.

SDK 7.14
Placement ID: 14755703

fun processNextAd() is doing check on top.
if (owner != null && this.getAdList() != null && !this.getAdList().isEmpty()) {
that check should ensure that baseAdResponse is not null. But it seams it is.
 
I would suggest to move that line in a front of IF check.

 final BaseAdResponse baseAdResponse = this.popAd();
 //and also check for baseAdResponse nullability
 if (owner != null && this.getAdList() != null && !this.getAdList().isEmpty() && baseAdResponse != null) {

**Comment by avohraa** [comment]
Hi @maxacmaxac, 

This issue has been addressed in latest release - https://github.com/appnexus/mobile-sdk-android/releases/tag/7.16
