### ISSUE TITLE
Native ad support for jetpack compose? 

### ISSUE THREAD

**Issue by miduch** [appnexus/mobile-sdk-android#67]
Is there any plan to support jetpack compose for native ad support? 

https://docs.xandr.com/bundle/mobile-sdk/page/show-banner-native-on-android.html

**Comment by yrajshekhar** [comment]
Hi @miduch , Have you looked into the [Android Developer Docs](https://developer.android.com/jetpack/compose/interop/interop-apis#views-in-compose).
Please let me know if you are facing any issue.

**Comment by miduch** [comment]
> Hi @miduch , Have you looked into the [Android Developer Docs](https://developer.android.com/jetpack/compose/interop/interop-apis#views-in-compose).
> Please let me know if you are facing any issue.

I meant compose support in your sdk. I am aware of possibility to use through AndroidView but it's not same as providing compose support in sdk

**Comment by avohraa** [comment]
Hi @miduch, we do not have plans to support JetPack compose natively in our SDK for now.
We do not feel there is a need to support JetPack compose in our SDK as our existing SDK works completely fine without any changes in JetPack compose.
We have created a Sample [Jetpack Compose app](https://github.com/appnexus/AppExamples/tree/master/Android/Kotlin/ComposeSample) using our SDK in Jetpack Compose app as an example if you need to use our SDK in a Jetpack compose app.

If you feel not having native support for Jetpack compose in our SDK impacts your business requirement please feel free to reach out through our official support page: https://help.xandr.com/ 
We will be able to do a formal review of the request and prioritize it.

**Comment by miduch** [comment]
@avohraa your samples are just very basic ones and none of it covers usecase when i think is very common one

1. LazyColumn in screen 
2. show banners in that LazyColumn  


Following within a LazyColumn will recreate banner ad whenever item becomes visible and destroy it when it goes offscreen. 
There has to be some way to re-use BannerAdView, if you try to cache  BannerAdView and reuse it you will end up with tons of leaks as internally BannerAdView has lot of listeners e.t.c. 

```
AndroidView(factory = { context ->
                       BannerAdView.apply {
                            this.loadAd()
                        }
                    })
```

As compose is future of android UI, you really need to comeup with a good solution. thanks!
