### ISSUE TITLE
com.appnexus.opensdk.ut.UTAdRequest.makeRequest System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'int org.json.JSONArray.length()' on a null object reference

### ISSUE THREAD

**Issue by paulrenn67** [appnexus/mobile-sdk-android#69]
Hi, we are getting this NPE from SDK version 7.19.1.  Was reported to you privately in our company Slack channels.

`12-16 11:26:06.870  1365  1477 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'int org.json.JSONArray.length()' on a null object reference
12-16 11:26:06.870  1365  1477 W System.err:    at com.appnexus.opensdk.ut.UTAdRequest.makeRequest(UTAdRequest.java:205)
12-16 11:26:06.871  1365  1477 W System.err:    at com.appnexus.opensdk.ut.UTAdRequest$AsyncRequest.doInBackground(UTAdRequest.java:247)
12-16 11:26:06.871  1365  1477 W System.err:    at com.appnexus.opensdk.ut.UTAdRequest$AsyncRequest.doInBackground(UTAdRequest.java:243)
12-16 11:26:06.871  1365  1477 W System.err:    at android.os.AsyncTask$3.call(AsyncTask.java:394)
12-16 11:26:06.871  1365  1477 W System.err:    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12-16 11:26:06.871  1365  1477 W System.err:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-16 11:26:06.871  1365  1477 W System.err:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-16 11:26:06.871  1365  1477 W System.err:    at java.lang.Thread.run(Thread.java:920)
12-16 11:26:06.872  1365  1477 E AppNexusClogListener: OPENSDK-REQUEST : E204: Ad couldn't be fetched due to unknown exception, see above trace.`

**Comment by avohraa** [comment]
We have addressed this issue in [7.20](https://github.com/appnexus/mobile-sdk-android/releases/tag/7.20). Please verify if that fixes the issue.
