### ISSUE TITLE
Xandr SDK v8.0 Removal Notice for Deprecated APIs 

### ISSUE THREAD

**Issue by Kowshickkarthick** [appnexus/mobile-sdk-android#71]
We Intent to remove all the deprecated APIs listed below in Xandr SDK v8.0. If you are using any of the below APIs we request to migrate to their equivalent. Do reach out to Xandr [support](https://help.xandr.com/s/login/) on questions or concerns.

| Class                   | Method(s)     |
| ------------------------|----------- |
| ANNativeAdResponse      |  isOpenNativeBrowser(),  openNativeBrowser(boolean openNativeBrowser)       |
| VideoAd               | getOpensNativeBrowser(), setOpensNativeBrowser(boolean opensNativeBrowser), setExternalUid(String externalUid), getExternalUid(), getCreativeId()        |
| ANMultiAdRequest | getExternalUid(), setExternalUid(String externalUid)|
| BannerAdView | loadAdOffscreen(), getOpensNativeBrowser(), setOpensNativeBrowser(boolean opensNativeBrowser), getExternalUid(), setExternalUid(String externalUid), getCreativeId(), getAdType(),setAllowNativeDemand(boolean enabled, int rendererId)|
| InterstitialAdView | loadAdOffscreen(), getOpensNativeBrowser(), setOpensNativeBrowser(boolean opensNativeBrowser), getExternalUid(), setExternalUid(String externalUid), getCreativeId(), getAdType()|
| NativeAdRequest | getOpensNativeBrowser(), setOpensNativeBrowser(boolean opensNativeBrowser), getExternalUid(), setExternalUid(String externalUid) |
| NativeAdResponse |  getCreativeId() , setCreativeId(String creativeId)|
| SDKSettings | useHttps(boolean useHttps), isHttpsEnabled(), setExternalUserIds(Map<ANExternalUserIdSource,String> externalUserIds), getExternalUserIds(), setAllowUsingSimpleDomain(boolean allow)|
| Clog | clogged (Variable) |
| ANExternalUserIdSource (enum)| |

**Comment by Kowshickkarthick** [comment]
Based on feedback methods `NativeAdRequest.getRendererId()` and `NativeAdRequest.setRendererId(int rendererId)` will not be removed.
Updated the description.

**Comment by avohraa** [comment]
Closing it, since this has been implemented and released in [SDK v8.0](https://github.com/appnexus/mobile-sdk-android/releases/tag/8.0).
