### ISSUE TITLE
Not a good way to use BannerAdView in LazyColumn (jetpack compose)

### ISSUE THREAD

**Issue by miduch** [appnexus/mobile-sdk-android#75]
A common usecase is to show banner ads in LazyColumn 

Following within a LazyColumn will recreate banner ad whenever item becomes visible and destroy it when it goes offscreen.
if you try to cache BannerAdView and reuse it you will end up with tons of leaks as internally BannerAdView has lot of listeners e.t.c.

```
AndroidView(factory = { context ->
                       BannerAdView.apply {
                            this.loadAd()
                        }
                    })

```

A better way to re-use BannerAdView in compose/ lazycolumn is missing  / None of provided samples covers this usecase

Related to 
https://github.com/appnexus/mobile-sdk-android/issues/67

**Comment by riteshzaveri** [comment]
Hello, @miduch 

Have you, by chance, looked at our LazyColumn Sample Banner App?

Please let us know if there are no issues so we can close this ticket.

**Comment by miduch** [comment]
Hi, yes i checked your example but i am afraid it was no where near actual/normal use cases. 

We have multi module app, with compose navigation e.t.c. the way you are caching those views in activity can't be used in our case 

If we try to cache these views inside a composeable that causes memory leaks.

**Comment by riteshzaveri** [comment]
As per our analysis, we can cache views inside composable functions. However, in our Sample [Jetpack Compose app](https://github.com/appnexus/AppExamples/tree/master/Android/Kotlin/ComposeSample), we demonstrate how views can be cached using LazyColumn and changed based on your business logic.

Do reach out to Xandr [support](https://help.xandr.com/s/login/) with questions or concerns and a sample application or code. We will be able to do a formal review of the request and prioritize it.
