### ISSUE TITLE
can not able to disable appnexus request/response log on logcat.

### ISSUE THREAD

**Issue by sanjaycvirtueinfo** [appnexus/mobile-sdk-android#79]
Currently i used below library on my apps

 implementation 'com.appnexus.opensdk:appnexus-sdk:7.22'
 implementation 'com.appnexus.opensdk.mediatedviews:appnexus-googleplay-mediation:[7,8)'
 
 i try  Clog.clogged = true; also but can not able to disable log. please help

**Comment by Kowshickkarthick** [comment]
We no longer release source code updates of Android SDK to Github. 
And this space is not monitored.
Please contact your account managers or submit a ticket via the Customer Support Portal: https://help.xandr.com/ if you have any questions.
