### ISSUE TITLE
Rewarded video ads and Rewarded Interstitial support in SDK and xandr adserver

### ISSUE THREAD

**Issue by amolrajoba** [appnexus/mobile-sdk-android#81]
Hi,
If possible please provide option for Rewarded video ads and Rewarded Interstitial ads support in this SDK and in xandr monetize adserver.

Thanks

**Comment by Kowshickkarthick** [comment]
We no longer release source code updates of Android SDK to Github. 
And this space is not monitored.
Please contact your account managers or submit a ticket via the Customer Support Portal: https://help.xandr.com/ if you have any questions.
