### ISSUE TITLE
RuntimeException: Using WebView from more than one process at once with the same data directory is not supported

### ISSUE THREAD

**Issue by FrancescoLombardiBurda** [appnexus/mobile-sdk-android#82]
Hi, please someone has some information regarding this topic? 

There's also Chromium bug opened on this. https://crbug.com/558377 

We didn't understand how to fix it. We got only the probably reason. 

The error message seems due to a change in Android Pie (API 28) and later version, which do not allow using a single WebView instance in two different processes.

have you in mind how to fix it? 

Thank you very much

**Comment by Kowshickkarthick** [comment]
We no longer release source code updates of Android SDK to Github. 
And this space is not monitored.
Please contact your account managers or submit a ticket via the Customer Support Portal: https://help.xandr.com/ if you have any questions.
