### ISSUE TITLE
AdView recomposition issue with Jetpack Compose

### ISSUE THREAD

**Issue by Vitanio** [appnexus/mobile-sdk-android#84]
Hi, we are migrating some of our views from standard layout to Jetpack Compose. During this process, we found out that there's a problem with the wrapping of BannerAdView inside the AndroidView composable. The overall implementation works quite well, but there is the following edge case:

- A banner is already loaded inside a state list. After some seconds, imagine that you need to insert another element in that list (without restarting the composition of the whole list). This process starts a recomposition of the list (recomposition, not composition). So here we expect to see the previous banner + the new element in that list. Unfortunately, this does not happen (the BannerAdView disappears until you scroll the view and then come back to that position). This happens only with BannerAdView (I've tested some other standard views like TextView, etc., which are working properly).
In order to exclude any specific issue related to our implementation (we used proper state handling and architecture), I tried the same scenario on your BannerLazyColumnActivity. The result is that I'm able to replicate the same issue in your code (I just made a few changes to the list).

Could you please check if there's a problem with the lifecycle of your view? 

Here your BannerLazyColumnActivity modified in order to replicate the issue:

`
@AndroidEntryPoint
class BannerLazyColumnActivity : AppCompatActivity() , AdListener {

    // List of cached banner ads list that populate the LazyColumn.
    private var cachedBannersList: ArrayList<BannerAdView> = java.util.ArrayList()

    // A banner ad is placed in every 50th position in the LazyColumn.
    private val adDisplayPos = 50

    override fun onCreate(savedInstanceState: Bundle?) {
        installSplashScreen()
        super.onCreate(savedInstanceState)

        // Update the LazyColumn item's list with member ids items and banner ads.
        populateListData()
        cacheBannerAds()

        setContent {
                Surface(color = MaterialTheme.colors.background) {

                    //Load LazyColumn Data
                    LoadLazyData()
                }

        }
    }

    @Composable
    fun LoadLazyData() {

        val listDataItems = remember { mutableStateListOf<Any>() }

        LaunchedEffect(Unit) {
            for (i in 1..2000) {
                listDataItems.add("Member Id $i")
            }
            while (true) {
                delay(30000)
                listDataItems.add(53, "New Item at ${System.currentTimeMillis()}")
            }
        }

        LazyColumn(
            modifier = Modifier
                .fillMaxSize(1f)
        ) {
            item {
                Row(
                    verticalAlignment = Alignment.CenterVertically,
                    horizontalArrangement = Arrangement.Center,
                    modifier = Modifier
                        .height(40.dp)
                        .fillMaxWidth()
                        .background(color = MaterialTheme.colors.primary)
                ) {
                    //Add title
                    Text(text = "Banner Lazy Column Ad", color = MaterialTheme.colors.background)
                }
            }
            itemsIndexed(listDataItems) { index, item ->

                if (index % adDisplayPos == 0) {

                    //Get List index
                    val listData : Any = listDataItems[index]

                    //Check if list index is string object or banner object and add banner in list

                    if (listData is BannerAdView) {
                        //On scrolling up check whether visible index has already a BannerAdView then load same banner
                        val bannerHasAd: BannerAdView = listDataItems[index] as BannerAdView
                        DisplayBannerAd(bannerHasAd)
                    }else if(listData is String) {
                        // This is while scrolling down. pop banner from the cached list and add it at the index postion and display the banner ad.
                        val bannerAdView: BannerAdView = pop(cachedBannersList)
                        listDataItems.add(index, bannerAdView)
                        DisplayBannerAd(bannerAdView)
                    }
                } else {
                    MemberIdItemsStyle(listDataItems[index] as String)
                }
            }
        }
    }

    /**
     * Remove old banner ads from the list and add new one.
     * @return
     */
    private fun pop(cachedBannersList: ArrayList<BannerAdView>): BannerAdView {

        // Cache a new banner Ad so that its ready when we come here next time.
        cacheBannerAds()
        return cachedBannersList.removeAt(0)
    }

    /**
     * Display banner ads from the list.
     */
    @Composable
    fun DisplayBannerAd(bannerAdView: BannerAdView) {

        Row(
            modifier = Modifier
                .fillMaxWidth()
                .padding(10.dp),
            verticalAlignment = Alignment.CenterVertically
        ) {

            // The BannerAdView recycled by the LazyColumn may be a different
            // instance than the one used previously for this position. Clear the
            // BannerAdView of any subviews in case it has a different
            // BannerAd associated with it, and make sure the BannerAd for this position doesn't
            // already have a parent of a different recycled BannerAdView.
            if (bannerAdView.parent != null) {
                (bannerAdView.parent as ViewGroup).removeView(bannerAdView)
            }

            //Returns the BannerAd
            AndroidView(factory = { context ->
                bannerAdView.apply {
                }
            })
        }
    }

    /**
     * Display member id from the list.
     */
    @Composable
    fun MemberIdItemsStyle(memberId: String) {

        //Displaying member id in Box style
        Box(
            modifier = Modifier
        ) {
            Row(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(16.dp),
                verticalAlignment = Alignment.CenterVertically
            ) {

                Column(
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(start = 12.dp)
                ) {

                    // Text that shows the member id
                    Text(
                        modifier = Modifier
                            .padding(top = 2.dp),
                        text = memberId,
                        maxLines = 1,
                        overflow = TextOverflow.Ellipsis,
                        style = TextStyle(
                            fontSize = 16.sp,
                        )
                    )
                }
            }
        }
    }

    /**
     * Add banner ads in the cached list.
     */
    private fun cacheBannerAds() {

        // create an instance of banner.
        val bannerAdView = BannerAdView(this)

        bannerAdView.setInventoryCodeAndMemberID(XXX, "xxx")

        // Get a 300x50 ad.
        bannerAdView.setAdSize(320, 50)

        // Set to 0 to disable auto-refresh.
        bannerAdView.autoRefreshInterval = 0

        // Turning this on so we always get an ad during testing.
        //bannerAdView.shouldServePSAs = true

        // Set whether ads will expand to fit the screen width.
        bannerAdView.expandsToFitScreenWidth = true

        bannerAdView.adListener = this

        //Set ad listener and load ad.
        bannerAdView.loadAd()

        cachedBannersList.add(bannerAdView)
    }

    /**
     * Add 200 member ids in list.
     */
    private fun populateListData() {

    }

    override fun onAdLoaded(p0: AdView?) {
    }

    override fun onAdLoaded(p0: NativeAdResponse?) {
    }

    override fun onAdRequestFailed(p0: AdView?, p1: ResultCode?) {
    }

    override fun onAdExpanded(p0: AdView?) {
    }

    override fun onAdCollapsed(p0: AdView?) {
    }

    override fun onAdClicked(p0: AdView?) {
    }

    override fun onAdClicked(p0: AdView?, p1: String?) {
    }

    override fun onLazyAdLoaded(p0: AdView?) {
    }

    override fun onAdImpression(p0: AdView?) {

    }
}
`
Before recomposition:
![before recomposition](https://github.com/appnexus/mobile-sdk-android/assets/5657606/26116a6b-9c00-485c-b97d-8b73bb3d4480)

After recomposition:
![after recomposition](https://github.com/appnexus/mobile-sdk-android/assets/5657606/794124bb-b905-4ea4-9256-b3ff0283070e)

**Comment by Kowshickkarthick** [comment]
Closing this ticket in GitHub for and acknowledging that the issue has been noted and will be triaged and fixed in future version. 
We no longer release source code updates of Android SDK to Github. 
And this space is not monitored.
Please contact your account managers or submit a ticket via the Customer Support Portal: https://help.xandr.com/ if you have any questions.
